disabled_rules:
    - trailing_whitespace
    - multiple_closures_with_trailing_closure
    - todo
    - convenience_type
    - for_where
    - force_unwrapping
    - large_tuple
    - force_cast
    - force_try
    - nesting    

only_rules:
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - explicit_init
    - fatal_error_message
    - file_name_no_space
    - first_where
    - last_where
    - flatmap_over_map_reduce
    - legacy_multiple
    - legacy_random
    - let_var_whitespace
    - literal_expression_end_indentation
    - multiline_arguments
    - multiline_function_chains
    - multiline_parameters
    - operator_usage_whitespace
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - reduce_into
    - sorted_first_last
    - yoda_condition

excluded:
    - ${PWD}/Carthage
    - ${PWD}/Pods
    - ${PWD}/SwiftLint/Common/3rdPartyLib
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 15
    error: 25
    
identifier_name:
    excluded:
        - id
        - ad
        - lhs
        - rhs
        - id
        - ad
        - zb
        - sm
        - wb
        - vc
        - vm
        - zh
        - x
        - y
        - i
        - j
        - k
        - x1
        - y1
    allowed_symbols: ["_"]
    
attributes:
    always_on_same_line: ["@discardableResult", "@objc", "@IBAction", "@IBDesignable", "@IBInspectable"]
    
reporter: "xcode"
